name: 'Compare Versions'
description: 'Compare current and previous versions of the code.'
branding:
  icon: 'tag'
  color: 'white'

inputs:
  repo-clone-url:
    description: > 
      The URL of the repository to clone. 
      
      If the repository is private, the URL must include a private access token.
      For example: `https://<token>@github.com/user/repo.git`
    required: true
  versions-extractor:
    description: 'Bash commands that should extract the version from the code.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check the environment
      shell: bash
      run: |
        pwd 
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "Action path: ${{ github.action_path }}"
        echo "Path: ${{ github.path }}"
        echo "===>"
    - name: Set the GitHub Path
      shell: bash
      run: | 
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        pwd 
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "Action path: ${{ github.action_path }}"
        echo "Path: ${{ github.path }}"
        echo "===>" 
    - name: Check the environment after setting the path
      shell: bash
      run: |
        pwd 
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "Action path: ${{ github.action_path }}"
        echo "Path: ${{ github.path }}"
        echo "===>"
    - name: Save extraction commands to a file
      shell: bash
      run: |
        pwd 
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "Action path: ${{ github.action_path }}"
        echo "Path: ${{ github.path }}"
        cat << EOF > ./versions-extractor-7602f6c0.sh
        #!/bin/bash
        ${{ inputs.versions-extractor }}
        EOF
        echo "Saved extraction commands to ./versions-extractor-7602f6c0.sh"
        cat ./versions-extractor-7602f6c0.sh
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "===>"
    - name: Extract and compare current and previous versions
      shell: bash
      run: |
        pwd 
        echo "----- ls -a -----"
        ls -a
        echo "-----------------"
        echo "Action path: ${{ github.action_path }}"
        echo "Path: ${{ github.path }}"
        ./scripts/compare-versions.sh \
          "${{ inputs.repo-clone-url }}" \
          "${{ github.event_name }}" \
          "${{ github.head_ref }}" \
          "${{ github.base_ref }}" \
          "${{ github.ref_name }}" \
          ./versions-extractor-7602f6c0.sh