name: 'Compare versions'
description: 'Compare current and previous versions of the code.'

inputs:
  repo-clone-url:
    description: > 
      The URL of the repository to clone. 
      
      If the repository is private, the URL must include a private access token.
      For example: `https://<token>@github.com/user/repo.git`
    required: true
  versions-extractor:
    description: 'Bash commands that should extract the version from the code.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check the environment
      run: ls -a
    - name: Save extraction commands to a file
      run: |
        cat << EOF > ./versions-extractor.sh
        #!/bin/bash
        "${{ inputs.versions-extractor }}"
        EOF
    - name: Extract and compare current and previous versions
      run: |
        ./scripts/compare-versions.sh \
          "${{ inputs.repo-clone-url }}" \
          "${{ github.event_name }}" \
          "${{ github.head_ref }}" \
          "${{ github.base_ref }}" \
          "${{ github.ref_name }}" \
          ./versions-extractor.sh