name: 'Compare Versions'
description: 'Compare current and previous versions of the code.'
branding:
  icon: 'tag'
  color: 'white'

inputs:
  repo-clone-url:
    description: > 
      The URL of the repository to clone. 
      Note: If the repository is private, the URL must include a private access token.
      For example: `https://token@github.com/user/repo.git`
    required: true
  versions-extractor:
    description: >
      Shell commands that should extract the version from the code. 
      The shell type is determined by the `shell` input.'
    required: true
  shell:
    description: 'The shell to use for running the commands. By default, it is set to `bash`.'
    default: 'bash'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Save extraction commands to a file
      shell: bash
      run: |
        shopt -s xpg_echo

        cd "${{ github.action_path }}"
        echo "====================================================="
        echo "Current working directory: $(pwd)"
        echo "Printing content of the action directory...\n"
        ls -la
        echo "====================================================="

        echo "Saving extraction commands to ./versions-extractor.sh"
        cat << EOF > ./versions-extractor.sh
        #!/bin/${{ inputs.shell }}

        ${{ inputs.versions-extractor }}
        EOF
        echo "-> ./versions-extractor.sh"
        nl -s ' | ' -b a ./versions-extractor.sh
        echo "====================================================="
    - name: Extract and compare current and previous versions
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        chmod +x ./src/main.sh
        ./src/main.sh \
          "${{ inputs.repo-clone-url }}" \
          "${{ github.event_name }}" \
          "${{ github.head_ref }}" \
          "${{ github.base_ref }}" \
          "${{ github.ref_name }}" \
          ./versions-extractor.sh